services:
    postgres:
        image: postgres:16-alpine
        container_name: osint-postgres
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - "pgdata:/var/lib/postgresql/data"
    rabbitmq:
        image: rabbitmq:management-alpine
        container_name: rabbitmq-osint
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"
    flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:latest
        container_name: flaresolverr
        restart: always
        ports:
            - "8191:8191"
        environment:
            LOG_LEVEL: info
    neo4j:
        image: neo4j:5.12-community
        container_name: neo4j-osint
        ports:
            - "7474:7474"
            - "7687:7687"
        environment:
            NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}

volumes:
    pgdata:
